// source: global_bot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var nlp_pb = require('./nlp_pb.js');
goog.object.extend(proto, nlp_pb);
var nlu_pb = require('./nlu_pb.js');
goog.object.extend(proto, nlu_pb);
var bot_housekeeping_pb = require('./bot_housekeeping_pb.js');
goog.object.extend(proto, bot_housekeeping_pb);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotConversationalReply', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotExtractedIntent', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotInput', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotIntent', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotIntentResult', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotReply', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotReplyType', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalIntentBot', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalIntentBot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.GlobalIntentBot.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalIntentBot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalIntentBot.displayName = 'proto.treeleaf.anydone.entities.GlobalIntentBot';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.GlobalBotInput.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotInput.displayName = 'proto.treeleaf.anydone.entities.GlobalBotInput';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotIntent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotIntent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotIntent.displayName = 'proto.treeleaf.anydone.entities.GlobalBotIntent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.GlobalBotIntentResult.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotIntentResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotIntentResult.displayName = 'proto.treeleaf.anydone.entities.GlobalBotIntentResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.GlobalBotConversationalReply.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotConversationalReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotConversationalReply.displayName = 'proto.treeleaf.anydone.entities.GlobalBotConversationalReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotExtractedIntent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.displayName = 'proto.treeleaf.anydone.entities.GlobalBotExtractedIntent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotReply.displayName = 'proto.treeleaf.anydone.entities.GlobalBotReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.displayName = 'proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalIntentBot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalIntentBot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.toObject = function(includeInstance, msg) {
  var f, obj = {
    intentname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    randomtrainingphrase: jspb.Message.getFieldWithDefault(msg, 2, ""),
    trainingphrasesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalIntentBot}
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalIntentBot;
  return proto.treeleaf.anydone.entities.GlobalIntentBot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalIntentBot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalIntentBot}
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntentname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRandomtrainingphrase(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addTrainingphrases(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalIntentBot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalIntentBot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntentname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRandomtrainingphrase();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTrainingphrasesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional string intentName = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.getIntentname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalIntentBot} returns this
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.setIntentname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string randomTrainingPhrase = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.getRandomtrainingphrase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalIntentBot} returns this
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.setRandomtrainingphrase = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string trainingPhrases = 3;
 * @return {!Array<string>}
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.getTrainingphrasesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.treeleaf.anydone.entities.GlobalIntentBot} returns this
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.setTrainingphrasesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.GlobalIntentBot} returns this
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.addTrainingphrases = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.GlobalIntentBot} returns this
 */
proto.treeleaf.anydone.entities.GlobalIntentBot.prototype.clearTrainingphrasesList = function() {
  return this.setTrainingphrasesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.GlobalBotInput.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotInput} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timezone: jspb.Message.getFieldWithDefault(msg, 2, ""),
    language: jspb.Message.getFieldWithDefault(msg, 3, ""),
    requestid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    accountid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    serviceid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    threshold: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    botversion: jspb.Message.getFieldWithDefault(msg, 8, ""),
    botid: jspb.Message.getFieldWithDefault(msg, 9, ""),
    botsetting: (f = msg.getBotsetting()) && bot_housekeeping_pb.BotSettings.toObject(includeInstance, f),
    intentlistList: jspb.Message.toObjectList(msg.getIntentlistList(),
    nlu_pb.IntentBot.toObject, includeInstance),
    isglobal: jspb.Message.getBooleanFieldWithDefault(msg, 12, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotInput;
  return proto.treeleaf.anydone.entities.GlobalBotInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimezone(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceid(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setThreshold(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotversion(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotid(value);
      break;
    case 10:
      var value = new bot_housekeeping_pb.BotSettings;
      reader.readMessage(value,bot_housekeeping_pb.BotSettings.deserializeBinaryFromReader);
      msg.setBotsetting(value);
      break;
    case 11:
      var value = new nlu_pb.IntentBot;
      reader.readMessage(value,nlu_pb.IntentBot.deserializeBinaryFromReader);
      msg.addIntentlist(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsglobal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotInput} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimezone();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRequestid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getServiceid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getThreshold();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getBotversion();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getBotid();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getBotsetting();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      bot_housekeeping_pb.BotSettings.serializeBinaryToWriter
    );
  }
  f = message.getIntentlistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      nlu_pb.IntentBot.serializeBinaryToWriter
    );
  }
  f = message.getIsglobal();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string timezone = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getTimezone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setTimezone = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string language = 3;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string requestId = 4;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getRequestid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setRequestid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string accountId = 5;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string serviceId = 6;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getServiceid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setServiceid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional float threshold = 7;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getThreshold = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setThreshold = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional string botVersion = 8;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getBotversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setBotversion = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string botId = 9;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getBotid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setBotid = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional BotSettings botsetting = 10;
 * @return {?proto.treeleaf.anydone.entities.BotSettings}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getBotsetting = function() {
  return /** @type{?proto.treeleaf.anydone.entities.BotSettings} */ (
    jspb.Message.getWrapperField(this, bot_housekeeping_pb.BotSettings, 10));
};


/**
 * @param {?proto.treeleaf.anydone.entities.BotSettings|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
*/
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setBotsetting = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.clearBotsetting = function() {
  return this.setBotsetting(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.hasBotsetting = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated IntentBot intentList = 11;
 * @return {!Array<!proto.treeleaf.anydone.entities.IntentBot>}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getIntentlistList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.IntentBot>} */ (
    jspb.Message.getRepeatedWrapperField(this, nlu_pb.IntentBot, 11));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.IntentBot>} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
*/
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setIntentlistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.IntentBot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.IntentBot}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.addIntentlist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.treeleaf.anydone.entities.IntentBot, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.clearIntentlistList = function() {
  return this.setIntentlistList([]);
};


/**
 * optional bool isglobal = 12;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.getIsglobal = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotInput.prototype.setIsglobal = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotIntent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotIntent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntent}
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotIntent;
  return proto.treeleaf.anydone.entities.GlobalBotIntent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotIntent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntent}
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotIntent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotIntent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double confidence = 2;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotIntent.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotIntentResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotIntentResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    intent: (f = msg.getIntent()) && nlu_pb.Intent.toObject(includeInstance, f),
    entitiesList: jspb.Message.toObjectList(msg.getEntitiesList(),
    nlp_pb.Entity.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntentResult}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotIntentResult;
  return proto.treeleaf.anydone.entities.GlobalBotIntentResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotIntentResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntentResult}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nlu_pb.Intent;
      reader.readMessage(value,nlu_pb.Intent.deserializeBinaryFromReader);
      msg.setIntent(value);
      break;
    case 2:
      var value = new nlp_pb.Entity;
      reader.readMessage(value,nlp_pb.Entity.deserializeBinaryFromReader);
      msg.addEntities(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotIntentResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotIntentResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      nlu_pb.Intent.serializeBinaryToWriter
    );
  }
  f = message.getEntitiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      nlp_pb.Entity.serializeBinaryToWriter
    );
  }
};


/**
 * optional Intent intent = 1;
 * @return {?proto.treeleaf.anydone.entities.Intent}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.getIntent = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Intent} */ (
    jspb.Message.getWrapperField(this, nlu_pb.Intent, 1));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Intent|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntentResult} returns this
*/
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.setIntent = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntentResult} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.clearIntent = function() {
  return this.setIntent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.hasIntent = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Entity entities = 2;
 * @return {!Array<!proto.treeleaf.anydone.entities.Entity>}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.getEntitiesList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.Entity>} */ (
    jspb.Message.getRepeatedWrapperField(this, nlp_pb.Entity, 2));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.Entity>} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntentResult} returns this
*/
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.setEntitiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.Entity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.Entity}
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.addEntities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.treeleaf.anydone.entities.Entity, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntentResult} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotIntentResult.prototype.clearEntitiesList = function() {
  return this.setEntitiesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotConversationalReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    intentresult: (f = msg.getIntentresult()) && nlu_pb.IntentResult.toObject(includeInstance, f),
    replytextList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply}
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotConversationalReply;
  return proto.treeleaf.anydone.entities.GlobalBotConversationalReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply}
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nlu_pb.IntentResult;
      reader.readMessage(value,nlu_pb.IntentResult.deserializeBinaryFromReader);
      msg.setIntentresult(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addReplytext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotConversationalReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntentresult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      nlu_pb.IntentResult.serializeBinaryToWriter
    );
  }
  f = message.getReplytextList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional IntentResult intentResult = 1;
 * @return {?proto.treeleaf.anydone.entities.IntentResult}
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.getIntentresult = function() {
  return /** @type{?proto.treeleaf.anydone.entities.IntentResult} */ (
    jspb.Message.getWrapperField(this, nlu_pb.IntentResult, 1));
};


/**
 * @param {?proto.treeleaf.anydone.entities.IntentResult|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} returns this
*/
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.setIntentresult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.clearIntentresult = function() {
  return this.setIntentresult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.hasIntentresult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string replyText = 2;
 * @return {!Array<string>}
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.getReplytextList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.setReplytextList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.addReplytext = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotConversationalReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotConversationalReply.prototype.clearReplytextList = function() {
  return this.setReplytextList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.toObject = function(includeInstance, msg) {
  var f, obj = {
    query: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intentname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    accountid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    serviceid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    botsettingid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    lang: jspb.Message.getFieldWithDefault(msg, 7, ""),
    latency: jspb.Message.getFieldWithDefault(msg, 8, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 9, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotExtractedIntent;
  return proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntentname(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConfidence(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotsettingid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLang(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setLatency(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntentname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getServiceid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getBotsettingid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLang();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getLatency();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional string query = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string intentName = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getIntentname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setIntentname = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double confidence = 3;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string accountId = 4;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string serviceId = 5;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getServiceid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setServiceid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string botSettingId = 6;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getBotsettingid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setBotsettingid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string lang = 7;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getLang = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setLang = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string latency = 8;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getLatency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setLatency = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int64 createdAt = 9;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 updatedAt = 10;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotExtractedIntent} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotExtractedIntent.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    conversationalreply: (f = msg.getConversationalreply()) && nlu_pb.ConversationalReply.toObject(includeInstance, f),
    replytype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    replymessage: jspb.Message.getFieldWithDefault(msg, 3, ""),
    metadata: (f = msg.getMetadata()) && nlu_pb.ExtractedIntent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotReply;
  return proto.treeleaf.anydone.entities.GlobalBotReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nlu_pb.ConversationalReply;
      reader.readMessage(value,nlu_pb.ConversationalReply.deserializeBinaryFromReader);
      msg.setConversationalreply(value);
      break;
    case 2:
      var value = /** @type {!proto.treeleaf.anydone.entities.BotReplyType} */ (reader.readEnum());
      msg.setReplytype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReplymessage(value);
      break;
    case 4:
      var value = new nlu_pb.ExtractedIntent;
      reader.readMessage(value,nlu_pb.ExtractedIntent.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConversationalreply();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      nlu_pb.ConversationalReply.serializeBinaryToWriter
    );
  }
  f = message.getReplytype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getReplymessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      nlu_pb.ExtractedIntent.serializeBinaryToWriter
    );
  }
};


/**
 * optional ConversationalReply conversationalReply = 1;
 * @return {?proto.treeleaf.anydone.entities.ConversationalReply}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.getConversationalreply = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ConversationalReply} */ (
    jspb.Message.getWrapperField(this, nlu_pb.ConversationalReply, 1));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ConversationalReply|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply} returns this
*/
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.setConversationalreply = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.clearConversationalreply = function() {
  return this.setConversationalreply(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.hasConversationalreply = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BotReplyType replyType = 2;
 * @return {!proto.treeleaf.anydone.entities.BotReplyType}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.getReplytype = function() {
  return /** @type {!proto.treeleaf.anydone.entities.BotReplyType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.BotReplyType} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.setReplytype = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string replyMessage = 3;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.getReplymessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.setReplymessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional ExtractedIntent metadata = 4;
 * @return {?proto.treeleaf.anydone.entities.ExtractedIntent}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.getMetadata = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ExtractedIntent} */ (
    jspb.Message.getWrapperField(this, nlu_pb.ExtractedIntent, 4));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ExtractedIntent|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply} returns this
*/
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalBotReply.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.toObject = function(includeInstance, msg) {
  var f, obj = {
    language: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage}
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage;
  return proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage}
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string language = 3;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.treeleaf.anydone.entities.GlobalBotReplyType = {
  GLOBAL_UNKNOWN_REPLY: 0,
  GLOBAL_CONVERSATIONAL_REPLY: 1,
  GLOBAL_DO_NOTHING_REPLY: 2,
  GLOBAL_WITH_MESSAGE_REPLY: 3
};

goog.object.extend(exports, proto.treeleaf.anydone.entities);
