// source: global_bot_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var auth_pb = require('./auth_pb.js');
goog.object.extend(proto, auth_pb);
var global_bot_pb = require('./global_bot_pb.js');
goog.object.extend(proto, global_bot_pb);
var bot_housekeeping_pb = require('./bot_housekeeping_pb.js');
goog.object.extend(proto, bot_housekeeping_pb);
goog.exportSymbol('proto.treeleaf.anydone.rpc.GlobalBotBaseRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.rpc.GlobalBotBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.GlobalBotBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.displayName = 'proto.treeleaf.anydone.rpc.GlobalBotBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.GlobalBotBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.displayName = 'proto.treeleaf.anydone.rpc.GlobalBotBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.repeatedFields_ = [3,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    intvalue: jspb.Message.getFieldWithDefault(msg, 4, 0),
    longvalue: jspb.Message.getFieldWithDefault(msg, 5, 0),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    doublevalue: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    isglobalbot: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    botinput: (f = msg.getBotinput()) && global_bot_pb.GlobalBotInput.toObject(includeInstance, f),
    botinputsList: jspb.Message.toObjectList(msg.getBotinputsList(),
    global_bot_pb.GlobalBotInput.toObject, includeInstance),
    botversion: (f = msg.getBotversion()) && bot_housekeeping_pb.BotVersion.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.GlobalBotBaseRequest;
  return proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongvalue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDoublevalue(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsglobalbot(value);
      break;
    case 9:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 10:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 11:
      var value = new global_bot_pb.GlobalBotInput;
      reader.readMessage(value,global_bot_pb.GlobalBotInput.deserializeBinaryFromReader);
      msg.setBotinput(value);
      break;
    case 12:
      var value = new global_bot_pb.GlobalBotInput;
      reader.readMessage(value,global_bot_pb.GlobalBotInput.deserializeBinaryFromReader);
      msg.addBotinputs(value);
      break;
    case 13:
      var value = new bot_housekeeping_pb.BotVersion;
      reader.readMessage(value,bot_housekeeping_pb.BotVersion.deserializeBinaryFromReader);
      msg.setBotversion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLongvalue();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBoolvalue();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDoublevalue();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getIsglobalbot();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getBotinput();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      global_bot_pb.GlobalBotInput.serializeBinaryToWriter
    );
  }
  f = message.getBotinputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      global_bot_pb.GlobalBotInput.serializeBinaryToWriter
    );
  }
  f = message.getBotversion();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      bot_housekeeping_pb.BotVersion.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional int32 intValue = 4;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 longValue = 5;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getLongvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setLongvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool boolValue = 6;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setBoolvalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool doubleValue = 7;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getDoublevalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setDoublevalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool isGlobalBot = 8;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getIsglobalbot = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setIsglobalbot = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional treeleaf.anydone.entities.Authorization authorization = 9;
 * @return {?proto.treeleaf.anydone.entities.Authorization}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 9));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Authorization|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional treeleaf.protos.Debug debug = 10;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 10));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional treeleaf.anydone.entities.GlobalBotInput botInput = 11;
 * @return {?proto.treeleaf.anydone.entities.GlobalBotInput}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getBotinput = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GlobalBotInput} */ (
    jspb.Message.getWrapperField(this, global_bot_pb.GlobalBotInput, 11));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GlobalBotInput|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setBotinput = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.clearBotinput = function() {
  return this.setBotinput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.hasBotinput = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated treeleaf.anydone.entities.GlobalBotInput botInputs = 12;
 * @return {!Array<!proto.treeleaf.anydone.entities.GlobalBotInput>}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getBotinputsList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.GlobalBotInput>} */ (
    jspb.Message.getRepeatedWrapperField(this, global_bot_pb.GlobalBotInput, 12));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.GlobalBotInput>} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setBotinputsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.GlobalBotInput=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.GlobalBotInput}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.addBotinputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.treeleaf.anydone.entities.GlobalBotInput, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.clearBotinputsList = function() {
  return this.setBotinputsList([]);
};


/**
 * optional treeleaf.anydone.entities.BotVersion botVersion = 13;
 * @return {?proto.treeleaf.anydone.entities.BotVersion}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.getBotversion = function() {
  return /** @type{?proto.treeleaf.anydone.entities.BotVersion} */ (
    jspb.Message.getWrapperField(this, bot_housekeeping_pb.BotVersion, 13));
};


/**
 * @param {?proto.treeleaf.anydone.entities.BotVersion|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.setBotversion = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.clearBotversion = function() {
  return this.setBotversion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseRequest.prototype.hasBotversion = function() {
  return jspb.Message.getField(this, 13) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.repeatedFields_ = [8,10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    timestamp: jspb.Message.getFieldWithDefault(msg, 5, 0),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    intentresult: (f = msg.getIntentresult()) && global_bot_pb.GlobalBotIntentResult.toObject(includeInstance, f),
    intentresultsList: jspb.Message.toObjectList(msg.getIntentresultsList(),
    global_bot_pb.GlobalBotIntentResult.toObject, includeInstance),
    botreply: (f = msg.getBotreply()) && global_bot_pb.GlobalBotReply.toObject(includeInstance, f),
    botrepliesList: jspb.Message.toObjectList(msg.getBotrepliesList(),
    global_bot_pb.GlobalBotReply.toObject, includeInstance),
    trainingphrasesList: jspb.Message.toObjectList(msg.getTrainingphrasesList(),
    bot_housekeeping_pb.TrainingPhrase.toObject, includeInstance),
    globalbotdetectedlanguage: (f = msg.getGlobalbotdetectedlanguage()) && global_bot_pb.GlobalBotDetectedLanguage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.GlobalBotBaseResponse;
  return proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 7:
      var value = new global_bot_pb.GlobalBotIntentResult;
      reader.readMessage(value,global_bot_pb.GlobalBotIntentResult.deserializeBinaryFromReader);
      msg.setIntentresult(value);
      break;
    case 8:
      var value = new global_bot_pb.GlobalBotIntentResult;
      reader.readMessage(value,global_bot_pb.GlobalBotIntentResult.deserializeBinaryFromReader);
      msg.addIntentresults(value);
      break;
    case 9:
      var value = new global_bot_pb.GlobalBotReply;
      reader.readMessage(value,global_bot_pb.GlobalBotReply.deserializeBinaryFromReader);
      msg.setBotreply(value);
      break;
    case 10:
      var value = new global_bot_pb.GlobalBotReply;
      reader.readMessage(value,global_bot_pb.GlobalBotReply.deserializeBinaryFromReader);
      msg.addBotreplies(value);
      break;
    case 11:
      var value = new bot_housekeeping_pb.TrainingPhrase;
      reader.readMessage(value,bot_housekeeping_pb.TrainingPhrase.deserializeBinaryFromReader);
      msg.addTrainingphrases(value);
      break;
    case 12:
      var value = new global_bot_pb.GlobalBotDetectedLanguage;
      reader.readMessage(value,global_bot_pb.GlobalBotDetectedLanguage.deserializeBinaryFromReader);
      msg.setGlobalbotdetectedlanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getIntentresult();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      global_bot_pb.GlobalBotIntentResult.serializeBinaryToWriter
    );
  }
  f = message.getIntentresultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      global_bot_pb.GlobalBotIntentResult.serializeBinaryToWriter
    );
  }
  f = message.getBotreply();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      global_bot_pb.GlobalBotReply.serializeBinaryToWriter
    );
  }
  f = message.getBotrepliesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      global_bot_pb.GlobalBotReply.serializeBinaryToWriter
    );
  }
  f = message.getTrainingphrasesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      bot_housekeeping_pb.TrainingPhrase.serializeBinaryToWriter
    );
  }
  f = message.getGlobalbotdetectedlanguage();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      global_bot_pb.GlobalBotDetectedLanguage.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 timestamp = 5;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional treeleaf.protos.Debug debug = 6;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 6));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional treeleaf.anydone.entities.GlobalBotIntentResult intentResult = 7;
 * @return {?proto.treeleaf.anydone.entities.GlobalBotIntentResult}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getIntentresult = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GlobalBotIntentResult} */ (
    jspb.Message.getWrapperField(this, global_bot_pb.GlobalBotIntentResult, 7));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GlobalBotIntentResult|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setIntentresult = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.clearIntentresult = function() {
  return this.setIntentresult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.hasIntentresult = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated treeleaf.anydone.entities.GlobalBotIntentResult intentResults = 8;
 * @return {!Array<!proto.treeleaf.anydone.entities.GlobalBotIntentResult>}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getIntentresultsList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.GlobalBotIntentResult>} */ (
    jspb.Message.getRepeatedWrapperField(this, global_bot_pb.GlobalBotIntentResult, 8));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.GlobalBotIntentResult>} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setIntentresultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.GlobalBotIntentResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.GlobalBotIntentResult}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.addIntentresults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.treeleaf.anydone.entities.GlobalBotIntentResult, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.clearIntentresultsList = function() {
  return this.setIntentresultsList([]);
};


/**
 * optional treeleaf.anydone.entities.GlobalBotReply botReply = 9;
 * @return {?proto.treeleaf.anydone.entities.GlobalBotReply}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getBotreply = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GlobalBotReply} */ (
    jspb.Message.getWrapperField(this, global_bot_pb.GlobalBotReply, 9));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GlobalBotReply|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setBotreply = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.clearBotreply = function() {
  return this.setBotreply(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.hasBotreply = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated treeleaf.anydone.entities.GlobalBotReply botReplies = 10;
 * @return {!Array<!proto.treeleaf.anydone.entities.GlobalBotReply>}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getBotrepliesList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.GlobalBotReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, global_bot_pb.GlobalBotReply, 10));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.GlobalBotReply>} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setBotrepliesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.GlobalBotReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.GlobalBotReply}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.addBotreplies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.treeleaf.anydone.entities.GlobalBotReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.clearBotrepliesList = function() {
  return this.setBotrepliesList([]);
};


/**
 * repeated treeleaf.anydone.entities.TrainingPhrase trainingPhrases = 11;
 * @return {!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getTrainingphrasesList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>} */ (
    jspb.Message.getRepeatedWrapperField(this, bot_housekeeping_pb.TrainingPhrase, 11));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setTrainingphrasesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.TrainingPhrase=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.TrainingPhrase}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.addTrainingphrases = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.treeleaf.anydone.entities.TrainingPhrase, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.clearTrainingphrasesList = function() {
  return this.setTrainingphrasesList([]);
};


/**
 * optional treeleaf.anydone.entities.GlobalBotDetectedLanguage globalBotDetectedLanguage = 12;
 * @return {?proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.getGlobalbotdetectedlanguage = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage} */ (
    jspb.Message.getWrapperField(this, global_bot_pb.GlobalBotDetectedLanguage, 12));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GlobalBotDetectedLanguage|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.setGlobalbotdetectedlanguage = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.GlobalBotBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.clearGlobalbotdetectedlanguage = function() {
  return this.setGlobalbotdetectedlanguage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.GlobalBotBaseResponse.prototype.hasGlobalbotdetectedlanguage = function() {
  return jspb.Message.getField(this, 12) != null;
};


goog.object.extend(exports, proto.treeleaf.anydone.rpc);
