// source: integration_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var integration_pb = require('./integration_pb.js');
goog.object.extend(proto, integration_pb);
var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var auth_pb = require('./auth_pb.js');
goog.object.extend(proto, auth_pb);
var user_pb = require('./user_pb.js');
goog.object.extend(proto, user_pb);
goog.exportSymbol('proto.treeleaf.anydone.rpc.IntegrationBaseRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.rpc.IntegrationBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.rpc.IntegrationBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.IntegrationBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.IntegrationBaseRequest.displayName = 'proto.treeleaf.anydone.rpc.IntegrationBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.rpc.IntegrationBaseResponse.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.IntegrationBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.IntegrationBaseResponse.displayName = 'proto.treeleaf.anydone.rpc.IntegrationBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.repeatedFields_ = [3,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.IntegrationBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    intvalue: jspb.Message.getFieldWithDefault(msg, 4, 0),
    longvalue: jspb.Message.getFieldWithDefault(msg, 5, 0),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    doublevalue: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    employee: (f = msg.getEmployee()) && user_pb.EmployeeProfile.toObject(includeInstance, f),
    employeesList: jspb.Message.toObjectList(msg.getEmployeesList(),
    user_pb.EmployeeProfile.toObject, includeInstance),
    serviceprovider: (f = msg.getServiceprovider()) && user_pb.ServiceProviderProfile.toObject(includeInstance, f),
    integration: (f = msg.getIntegration()) && integration_pb.Integration.toObject(includeInstance, f),
    thirdpartyapi: (f = msg.getThirdpartyapi()) && integration_pb.ThirdPartyApi.toObject(includeInstance, f),
    integrationfilter: (f = msg.getIntegrationfilter()) && integration_pb.IntegrationFilter.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.IntegrationBaseRequest;
  return proto.treeleaf.anydone.rpc.IntegrationBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongvalue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDoublevalue(value);
      break;
    case 8:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 9:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 10:
      var value = new user_pb.EmployeeProfile;
      reader.readMessage(value,user_pb.EmployeeProfile.deserializeBinaryFromReader);
      msg.setEmployee(value);
      break;
    case 11:
      var value = new user_pb.EmployeeProfile;
      reader.readMessage(value,user_pb.EmployeeProfile.deserializeBinaryFromReader);
      msg.addEmployees(value);
      break;
    case 12:
      var value = new user_pb.ServiceProviderProfile;
      reader.readMessage(value,user_pb.ServiceProviderProfile.deserializeBinaryFromReader);
      msg.setServiceprovider(value);
      break;
    case 13:
      var value = new integration_pb.Integration;
      reader.readMessage(value,integration_pb.Integration.deserializeBinaryFromReader);
      msg.setIntegration(value);
      break;
    case 14:
      var value = new integration_pb.ThirdPartyApi;
      reader.readMessage(value,integration_pb.ThirdPartyApi.deserializeBinaryFromReader);
      msg.setThirdpartyapi(value);
      break;
    case 15:
      var value = new integration_pb.IntegrationFilter;
      reader.readMessage(value,integration_pb.IntegrationFilter.deserializeBinaryFromReader);
      msg.setIntegrationfilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.IntegrationBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLongvalue();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBoolvalue();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDoublevalue();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getEmployee();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      user_pb.EmployeeProfile.serializeBinaryToWriter
    );
  }
  f = message.getEmployeesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      user_pb.EmployeeProfile.serializeBinaryToWriter
    );
  }
  f = message.getServiceprovider();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      user_pb.ServiceProviderProfile.serializeBinaryToWriter
    );
  }
  f = message.getIntegration();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      integration_pb.Integration.serializeBinaryToWriter
    );
  }
  f = message.getThirdpartyapi();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      integration_pb.ThirdPartyApi.serializeBinaryToWriter
    );
  }
  f = message.getIntegrationfilter();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      integration_pb.IntegrationFilter.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional int32 intValue = 4;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 longValue = 5;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getLongvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setLongvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool boolValue = 6;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setBoolvalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool doubleValue = 7;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getDoublevalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setDoublevalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional treeleaf.anydone.entities.Authorization authorization = 8;
 * @return {?proto.treeleaf.anydone.entities.Authorization}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 8));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Authorization|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional treeleaf.protos.Debug debug = 9;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 9));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional treeleaf.anydone.entities.EmployeeProfile employee = 10;
 * @return {?proto.treeleaf.anydone.entities.EmployeeProfile}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getEmployee = function() {
  return /** @type{?proto.treeleaf.anydone.entities.EmployeeProfile} */ (
    jspb.Message.getWrapperField(this, user_pb.EmployeeProfile, 10));
};


/**
 * @param {?proto.treeleaf.anydone.entities.EmployeeProfile|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setEmployee = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearEmployee = function() {
  return this.setEmployee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.hasEmployee = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated treeleaf.anydone.entities.EmployeeProfile employees = 11;
 * @return {!Array<!proto.treeleaf.anydone.entities.EmployeeProfile>}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getEmployeesList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.EmployeeProfile>} */ (
    jspb.Message.getRepeatedWrapperField(this, user_pb.EmployeeProfile, 11));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.EmployeeProfile>} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setEmployeesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.EmployeeProfile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.EmployeeProfile}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.addEmployees = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.treeleaf.anydone.entities.EmployeeProfile, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearEmployeesList = function() {
  return this.setEmployeesList([]);
};


/**
 * optional treeleaf.anydone.entities.ServiceProviderProfile serviceProvider = 12;
 * @return {?proto.treeleaf.anydone.entities.ServiceProviderProfile}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getServiceprovider = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ServiceProviderProfile} */ (
    jspb.Message.getWrapperField(this, user_pb.ServiceProviderProfile, 12));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ServiceProviderProfile|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setServiceprovider = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearServiceprovider = function() {
  return this.setServiceprovider(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.hasServiceprovider = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional treeleaf.anydone.entities.Integration integration = 13;
 * @return {?proto.treeleaf.anydone.entities.Integration}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getIntegration = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Integration} */ (
    jspb.Message.getWrapperField(this, integration_pb.Integration, 13));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Integration|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setIntegration = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearIntegration = function() {
  return this.setIntegration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.hasIntegration = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional treeleaf.anydone.entities.ThirdPartyApi thirdPartyApi = 14;
 * @return {?proto.treeleaf.anydone.entities.ThirdPartyApi}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getThirdpartyapi = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ThirdPartyApi} */ (
    jspb.Message.getWrapperField(this, integration_pb.ThirdPartyApi, 14));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ThirdPartyApi|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setThirdpartyapi = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearThirdpartyapi = function() {
  return this.setThirdpartyapi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.hasThirdpartyapi = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional treeleaf.anydone.entities.IntegrationFilter integrationFilter = 15;
 * @return {?proto.treeleaf.anydone.entities.IntegrationFilter}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.getIntegrationfilter = function() {
  return /** @type{?proto.treeleaf.anydone.entities.IntegrationFilter} */ (
    jspb.Message.getWrapperField(this, integration_pb.IntegrationFilter, 15));
};


/**
 * @param {?proto.treeleaf.anydone.entities.IntegrationFilter|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.setIntegrationfilter = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.clearIntegrationfilter = function() {
  return this.setIntegrationfilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseRequest.prototype.hasIntegrationfilter = function() {
  return jspb.Message.getField(this, 15) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.repeatedFields_ = [7,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.IntegrationBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    integration: (f = msg.getIntegration()) && integration_pb.Integration.toObject(includeInstance, f),
    integrationsList: jspb.Message.toObjectList(msg.getIntegrationsList(),
    integration_pb.Integration.toObject, includeInstance),
    thirdpartyapi: (f = msg.getThirdpartyapi()) && integration_pb.ThirdPartyApi.toObject(includeInstance, f),
    thirdpartyapisList: jspb.Message.toObjectList(msg.getThirdpartyapisList(),
    integration_pb.ThirdPartyApi.toObject, includeInstance),
    generatedemail: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.IntegrationBaseResponse;
  return proto.treeleaf.anydone.rpc.IntegrationBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 6:
      var value = new integration_pb.Integration;
      reader.readMessage(value,integration_pb.Integration.deserializeBinaryFromReader);
      msg.setIntegration(value);
      break;
    case 7:
      var value = new integration_pb.Integration;
      reader.readMessage(value,integration_pb.Integration.deserializeBinaryFromReader);
      msg.addIntegrations(value);
      break;
    case 8:
      var value = new integration_pb.ThirdPartyApi;
      reader.readMessage(value,integration_pb.ThirdPartyApi.deserializeBinaryFromReader);
      msg.setThirdpartyapi(value);
      break;
    case 9:
      var value = new integration_pb.ThirdPartyApi;
      reader.readMessage(value,integration_pb.ThirdPartyApi.deserializeBinaryFromReader);
      msg.addThirdpartyapis(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setGeneratedemail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.IntegrationBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getIntegration();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      integration_pb.Integration.serializeBinaryToWriter
    );
  }
  f = message.getIntegrationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      integration_pb.Integration.serializeBinaryToWriter
    );
  }
  f = message.getThirdpartyapi();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      integration_pb.ThirdPartyApi.serializeBinaryToWriter
    );
  }
  f = message.getThirdpartyapisList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      integration_pb.ThirdPartyApi.serializeBinaryToWriter
    );
  }
  f = message.getGeneratedemail();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional treeleaf.protos.Debug debug = 5;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 5));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional treeleaf.anydone.entities.Integration integration = 6;
 * @return {?proto.treeleaf.anydone.entities.Integration}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getIntegration = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Integration} */ (
    jspb.Message.getWrapperField(this, integration_pb.Integration, 6));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Integration|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setIntegration = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.clearIntegration = function() {
  return this.setIntegration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.hasIntegration = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated treeleaf.anydone.entities.Integration integrations = 7;
 * @return {!Array<!proto.treeleaf.anydone.entities.Integration>}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getIntegrationsList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.Integration>} */ (
    jspb.Message.getRepeatedWrapperField(this, integration_pb.Integration, 7));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.Integration>} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setIntegrationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.Integration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.Integration}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.addIntegrations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.treeleaf.anydone.entities.Integration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.clearIntegrationsList = function() {
  return this.setIntegrationsList([]);
};


/**
 * optional treeleaf.anydone.entities.ThirdPartyApi thirdPartyApi = 8;
 * @return {?proto.treeleaf.anydone.entities.ThirdPartyApi}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getThirdpartyapi = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ThirdPartyApi} */ (
    jspb.Message.getWrapperField(this, integration_pb.ThirdPartyApi, 8));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ThirdPartyApi|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setThirdpartyapi = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.clearThirdpartyapi = function() {
  return this.setThirdpartyapi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.hasThirdpartyapi = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated treeleaf.anydone.entities.ThirdPartyApi thirdPartyApis = 9;
 * @return {!Array<!proto.treeleaf.anydone.entities.ThirdPartyApi>}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getThirdpartyapisList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.ThirdPartyApi>} */ (
    jspb.Message.getRepeatedWrapperField(this, integration_pb.ThirdPartyApi, 9));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.ThirdPartyApi>} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setThirdpartyapisList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.ThirdPartyApi=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.ThirdPartyApi}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.addThirdpartyapis = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.treeleaf.anydone.entities.ThirdPartyApi, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.clearThirdpartyapisList = function() {
  return this.setThirdpartyapisList([]);
};


/**
 * optional string generatedEmail = 10;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.getGeneratedemail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.IntegrationBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.IntegrationBaseResponse.prototype.setGeneratedemail = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


goog.object.extend(exports, proto.treeleaf.anydone.rpc);
