// source: settings_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var settings_pb = require('./settings_pb.js');
goog.object.extend(proto, settings_pb);
var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var auth_pb = require('./auth_pb.js');
goog.object.extend(proto, auth_pb);
goog.exportSymbol('proto.treeleaf.anydone.rpc.SettingsBaseRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.rpc.SettingsBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.rpc.SettingsBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.SettingsBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.SettingsBaseRequest.displayName = 'proto.treeleaf.anydone.rpc.SettingsBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.SettingsBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.SettingsBaseResponse.displayName = 'proto.treeleaf.anydone.rpc.SettingsBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.SettingsBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    generalsettings: (f = msg.getGeneralsettings()) && settings_pb.GeneralSettings.toObject(includeInstance, f),
    inboxsettings: (f = msg.getInboxsettings()) && settings_pb.InboxSettings.toObject(includeInstance, f),
    botsettings: (f = msg.getBotsettings()) && settings_pb.GlobalBotSettings.toObject(includeInstance, f),
    meetsettings: (f = msg.getMeetsettings()) && settings_pb.MeetSettings.toObject(includeInstance, f),
    accountsettings: (f = msg.getAccountsettings()) && settings_pb.AccountSettings.toObject(includeInstance, f),
    ticketsettings: (f = msg.getTicketsettings()) && settings_pb.GloablTicketSettings.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.SettingsBaseRequest;
  return proto.treeleaf.anydone.rpc.SettingsBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 5:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 6:
      var value = new settings_pb.GeneralSettings;
      reader.readMessage(value,settings_pb.GeneralSettings.deserializeBinaryFromReader);
      msg.setGeneralsettings(value);
      break;
    case 7:
      var value = new settings_pb.InboxSettings;
      reader.readMessage(value,settings_pb.InboxSettings.deserializeBinaryFromReader);
      msg.setInboxsettings(value);
      break;
    case 8:
      var value = new settings_pb.GlobalBotSettings;
      reader.readMessage(value,settings_pb.GlobalBotSettings.deserializeBinaryFromReader);
      msg.setBotsettings(value);
      break;
    case 9:
      var value = new settings_pb.MeetSettings;
      reader.readMessage(value,settings_pb.MeetSettings.deserializeBinaryFromReader);
      msg.setMeetsettings(value);
      break;
    case 10:
      var value = new settings_pb.AccountSettings;
      reader.readMessage(value,settings_pb.AccountSettings.deserializeBinaryFromReader);
      msg.setAccountsettings(value);
      break;
    case 11:
      var value = new settings_pb.GloablTicketSettings;
      reader.readMessage(value,settings_pb.GloablTicketSettings.deserializeBinaryFromReader);
      msg.setTicketsettings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.SettingsBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getGeneralsettings();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      settings_pb.GeneralSettings.serializeBinaryToWriter
    );
  }
  f = message.getInboxsettings();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      settings_pb.InboxSettings.serializeBinaryToWriter
    );
  }
  f = message.getBotsettings();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      settings_pb.GlobalBotSettings.serializeBinaryToWriter
    );
  }
  f = message.getMeetsettings();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      settings_pb.MeetSettings.serializeBinaryToWriter
    );
  }
  f = message.getAccountsettings();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      settings_pb.AccountSettings.serializeBinaryToWriter
    );
  }
  f = message.getTicketsettings();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      settings_pb.GloablTicketSettings.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional treeleaf.protos.Debug debug = 4;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 4));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional treeleaf.anydone.entities.Authorization authorization = 5;
 * @return {?proto.treeleaf.anydone.entities.Authorization}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 5));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Authorization|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional treeleaf.anydone.entities.GeneralSettings generalSettings = 6;
 * @return {?proto.treeleaf.anydone.entities.GeneralSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getGeneralsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GeneralSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.GeneralSettings, 6));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GeneralSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setGeneralsettings = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearGeneralsettings = function() {
  return this.setGeneralsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasGeneralsettings = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional treeleaf.anydone.entities.InboxSettings inboxSettings = 7;
 * @return {?proto.treeleaf.anydone.entities.InboxSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getInboxsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.InboxSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.InboxSettings, 7));
};


/**
 * @param {?proto.treeleaf.anydone.entities.InboxSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setInboxsettings = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearInboxsettings = function() {
  return this.setInboxsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasInboxsettings = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional treeleaf.anydone.entities.GlobalBotSettings botSettings = 8;
 * @return {?proto.treeleaf.anydone.entities.GlobalBotSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getBotsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GlobalBotSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.GlobalBotSettings, 8));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GlobalBotSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setBotsettings = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearBotsettings = function() {
  return this.setBotsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasBotsettings = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional treeleaf.anydone.entities.MeetSettings meetSettings = 9;
 * @return {?proto.treeleaf.anydone.entities.MeetSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getMeetsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.MeetSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.MeetSettings, 9));
};


/**
 * @param {?proto.treeleaf.anydone.entities.MeetSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setMeetsettings = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearMeetsettings = function() {
  return this.setMeetsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasMeetsettings = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional treeleaf.anydone.entities.AccountSettings accountSettings = 10;
 * @return {?proto.treeleaf.anydone.entities.AccountSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getAccountsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.AccountSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.AccountSettings, 10));
};


/**
 * @param {?proto.treeleaf.anydone.entities.AccountSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setAccountsettings = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearAccountsettings = function() {
  return this.setAccountsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasAccountsettings = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional treeleaf.anydone.entities.GloablTicketSettings ticketSettings = 11;
 * @return {?proto.treeleaf.anydone.entities.GloablTicketSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.getTicketsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GloablTicketSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.GloablTicketSettings, 11));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GloablTicketSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.setTicketsettings = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.clearTicketsettings = function() {
  return this.setTicketsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseRequest.prototype.hasTicketsettings = function() {
  return jspb.Message.getField(this, 11) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.SettingsBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    timestamp: jspb.Message.getFieldWithDefault(msg, 5, 0),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    generalsettings: (f = msg.getGeneralsettings()) && settings_pb.GeneralSettings.toObject(includeInstance, f),
    inboxsettings: (f = msg.getInboxsettings()) && settings_pb.InboxSettings.toObject(includeInstance, f),
    botsettings: (f = msg.getBotsettings()) && settings_pb.GlobalBotSettings.toObject(includeInstance, f),
    meetsettings: (f = msg.getMeetsettings()) && settings_pb.MeetSettings.toObject(includeInstance, f),
    accountsettings: (f = msg.getAccountsettings()) && settings_pb.AccountSettings.toObject(includeInstance, f),
    ticketsettings: (f = msg.getTicketsettings()) && settings_pb.GloablTicketSettings.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.SettingsBaseResponse;
  return proto.treeleaf.anydone.rpc.SettingsBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 7:
      var value = new settings_pb.GeneralSettings;
      reader.readMessage(value,settings_pb.GeneralSettings.deserializeBinaryFromReader);
      msg.setGeneralsettings(value);
      break;
    case 8:
      var value = new settings_pb.InboxSettings;
      reader.readMessage(value,settings_pb.InboxSettings.deserializeBinaryFromReader);
      msg.setInboxsettings(value);
      break;
    case 9:
      var value = new settings_pb.GlobalBotSettings;
      reader.readMessage(value,settings_pb.GlobalBotSettings.deserializeBinaryFromReader);
      msg.setBotsettings(value);
      break;
    case 10:
      var value = new settings_pb.MeetSettings;
      reader.readMessage(value,settings_pb.MeetSettings.deserializeBinaryFromReader);
      msg.setMeetsettings(value);
      break;
    case 11:
      var value = new settings_pb.AccountSettings;
      reader.readMessage(value,settings_pb.AccountSettings.deserializeBinaryFromReader);
      msg.setAccountsettings(value);
      break;
    case 12:
      var value = new settings_pb.GloablTicketSettings;
      reader.readMessage(value,settings_pb.GloablTicketSettings.deserializeBinaryFromReader);
      msg.setTicketsettings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.SettingsBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getGeneralsettings();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      settings_pb.GeneralSettings.serializeBinaryToWriter
    );
  }
  f = message.getInboxsettings();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      settings_pb.InboxSettings.serializeBinaryToWriter
    );
  }
  f = message.getBotsettings();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      settings_pb.GlobalBotSettings.serializeBinaryToWriter
    );
  }
  f = message.getMeetsettings();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      settings_pb.MeetSettings.serializeBinaryToWriter
    );
  }
  f = message.getAccountsettings();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      settings_pb.AccountSettings.serializeBinaryToWriter
    );
  }
  f = message.getTicketsettings();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      settings_pb.GloablTicketSettings.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 timestamp = 5;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional treeleaf.protos.Debug debug = 6;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 6));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional treeleaf.anydone.entities.GeneralSettings generalSettings = 7;
 * @return {?proto.treeleaf.anydone.entities.GeneralSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getGeneralsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GeneralSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.GeneralSettings, 7));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GeneralSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setGeneralsettings = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.clearGeneralsettings = function() {
  return this.setGeneralsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.hasGeneralsettings = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional treeleaf.anydone.entities.InboxSettings inboxSettings = 8;
 * @return {?proto.treeleaf.anydone.entities.InboxSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getInboxsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.InboxSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.InboxSettings, 8));
};


/**
 * @param {?proto.treeleaf.anydone.entities.InboxSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setInboxsettings = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.clearInboxsettings = function() {
  return this.setInboxsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.hasInboxsettings = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional treeleaf.anydone.entities.GlobalBotSettings botSettings = 9;
 * @return {?proto.treeleaf.anydone.entities.GlobalBotSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getBotsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GlobalBotSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.GlobalBotSettings, 9));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GlobalBotSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setBotsettings = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.clearBotsettings = function() {
  return this.setBotsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.hasBotsettings = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional treeleaf.anydone.entities.MeetSettings meetSettings = 10;
 * @return {?proto.treeleaf.anydone.entities.MeetSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getMeetsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.MeetSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.MeetSettings, 10));
};


/**
 * @param {?proto.treeleaf.anydone.entities.MeetSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setMeetsettings = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.clearMeetsettings = function() {
  return this.setMeetsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.hasMeetsettings = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional treeleaf.anydone.entities.AccountSettings accountSettings = 11;
 * @return {?proto.treeleaf.anydone.entities.AccountSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getAccountsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.AccountSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.AccountSettings, 11));
};


/**
 * @param {?proto.treeleaf.anydone.entities.AccountSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setAccountsettings = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.clearAccountsettings = function() {
  return this.setAccountsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.hasAccountsettings = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional treeleaf.anydone.entities.GloablTicketSettings ticketSettings = 12;
 * @return {?proto.treeleaf.anydone.entities.GloablTicketSettings}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.getTicketsettings = function() {
  return /** @type{?proto.treeleaf.anydone.entities.GloablTicketSettings} */ (
    jspb.Message.getWrapperField(this, settings_pb.GloablTicketSettings, 12));
};


/**
 * @param {?proto.treeleaf.anydone.entities.GloablTicketSettings|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.setTicketsettings = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.SettingsBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.clearTicketsettings = function() {
  return this.setTicketsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.SettingsBaseResponse.prototype.hasTicketsettings = function() {
  return jspb.Message.getField(this, 12) != null;
};


goog.object.extend(exports, proto.treeleaf.anydone.rpc);
