// source: settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.treeleaf.anydone.entities.AccountSettings', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GeneralSettings', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GloablTicketSettings', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GloablTicketSettings.TicketAccessControl', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalBotSettings', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.InboxSettings', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.InboxSettings.AccessControlType', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.MeetSettings', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GeneralSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GeneralSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GeneralSettings.displayName = 'proto.treeleaf.anydone.entities.GeneralSettings';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.InboxSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.InboxSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.InboxSettings.displayName = 'proto.treeleaf.anydone.entities.InboxSettings';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalBotSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalBotSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalBotSettings.displayName = 'proto.treeleaf.anydone.entities.GlobalBotSettings';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.MeetSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.MeetSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.MeetSettings.displayName = 'proto.treeleaf.anydone.entities.MeetSettings';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.AccountSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.AccountSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.AccountSettings.displayName = 'proto.treeleaf.anydone.entities.AccountSettings';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GloablTicketSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GloablTicketSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GloablTicketSettings.displayName = 'proto.treeleaf.anydone.entities.GloablTicketSettings';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GeneralSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GeneralSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GeneralSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    generalsettingid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    language: jspb.Message.getFieldWithDefault(msg, 2, ""),
    donotdisturb: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createdat: jspb.Message.getFieldWithDefault(msg, 4, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GeneralSettings}
 */
proto.treeleaf.anydone.entities.GeneralSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GeneralSettings;
  return proto.treeleaf.anydone.entities.GeneralSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GeneralSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GeneralSettings}
 */
proto.treeleaf.anydone.entities.GeneralSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGeneralsettingid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDonotdisturb(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GeneralSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GeneralSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GeneralSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGeneralsettingid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDonotdisturb();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string generalSettingId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.getGeneralsettingid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GeneralSettings} returns this
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.setGeneralsettingid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string language = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GeneralSettings} returns this
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 doNotDisturb = 3;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.getDonotdisturb = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GeneralSettings} returns this
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.setDonotdisturb = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 createdAt = 4;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GeneralSettings} returns this
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 updatedAt = 5;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GeneralSettings} returns this
 */
proto.treeleaf.anydone.entities.GeneralSettings.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.InboxSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.InboxSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.InboxSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    inboxsettingsid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createprivategroupby: jspb.Message.getFieldWithDefault(msg, 2, 0),
    createpublicgroupby: jspb.Message.getFieldWithDefault(msg, 3, 0),
    archiveprivategroupby: jspb.Message.getFieldWithDefault(msg, 4, 0),
    archivepublicgroupby: jspb.Message.getFieldWithDefault(msg, 5, 0),
    caneditmessage: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    candeletemessage: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    canreplyinprivategroups: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    createdat: jspb.Message.getFieldWithDefault(msg, 9, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.InboxSettings}
 */
proto.treeleaf.anydone.entities.InboxSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.InboxSettings;
  return proto.treeleaf.anydone.entities.InboxSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.InboxSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.InboxSettings}
 */
proto.treeleaf.anydone.entities.InboxSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInboxsettingsid(value);
      break;
    case 2:
      var value = /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (reader.readEnum());
      msg.setCreateprivategroupby(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (reader.readEnum());
      msg.setCreatepublicgroupby(value);
      break;
    case 4:
      var value = /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (reader.readEnum());
      msg.setArchiveprivategroupby(value);
      break;
    case 5:
      var value = /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (reader.readEnum());
      msg.setArchivepublicgroupby(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCaneditmessage(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCandeletemessage(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCanreplyinprivategroups(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.InboxSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.InboxSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.InboxSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInboxsettingsid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreateprivategroupby();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getCreatepublicgroupby();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getArchiveprivategroupby();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getArchivepublicgroupby();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getCaneditmessage();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getCandeletemessage();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getCanreplyinprivategroups();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.treeleaf.anydone.entities.InboxSettings.AccessControlType = {
  UNKNOWN: 0,
  ADMIN: 1,
  EVERYONE: 2,
  EVERYONE_EXCEPT_GUEST: 3
};

/**
 * optional string inboxSettingsId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getInboxsettingsid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setInboxsettingsid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional AccessControlType createPrivateGroupBy = 2;
 * @return {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getCreateprivategroupby = function() {
  return /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setCreateprivategroupby = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional AccessControlType createPublicGroupBy = 3;
 * @return {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getCreatepublicgroupby = function() {
  return /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setCreatepublicgroupby = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional AccessControlType archivePrivateGroupBy = 4;
 * @return {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getArchiveprivategroupby = function() {
  return /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setArchiveprivategroupby = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional AccessControlType archivePublicGroupBy = 5;
 * @return {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getArchivepublicgroupby = function() {
  return /** @type {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.InboxSettings.AccessControlType} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setArchivepublicgroupby = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional bool canEditMessage = 6;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getCaneditmessage = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setCaneditmessage = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool canDeleteMessage = 7;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getCandeletemessage = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setCandeletemessage = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool canReplyInPrivateGroups = 8;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getCanreplyinprivategroups = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setCanreplyinprivategroups = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional int64 createdAt = 9;
 * @return {number}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 updatedAt = 10;
 * @return {number}
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.InboxSettings} returns this
 */
proto.treeleaf.anydone.entities.InboxSettings.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalBotSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalBotSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    botsettingid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    language: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timezone: jspb.Message.getFieldWithDefault(msg, 3, ""),
    threshold: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    createdat: jspb.Message.getFieldWithDefault(msg, 5, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalBotSettings;
  return proto.treeleaf.anydone.entities.GlobalBotSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotsettingid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimezone(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setThreshold(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalBotSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalBotSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBotsettingid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimezone();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getThreshold();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional string botSettingId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.getBotsettingid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.setBotsettingid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string language = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string timezone = 3;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.getTimezone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.setTimezone = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float threshold = 4;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.getThreshold = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.setThreshold = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int64 createdAt = 5;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 updatedAt = 6;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GlobalBotSettings} returns this
 */
proto.treeleaf.anydone.entities.GlobalBotSettings.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.MeetSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.MeetSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.MeetSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    meetsettingid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    caninviteguest: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    shouldverifyguestemail: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    canimportthirdpartycalendar: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    createdat: jspb.Message.getFieldWithDefault(msg, 5, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.MeetSettings}
 */
proto.treeleaf.anydone.entities.MeetSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.MeetSettings;
  return proto.treeleaf.anydone.entities.MeetSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.MeetSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.MeetSettings}
 */
proto.treeleaf.anydone.entities.MeetSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMeetsettingid(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCaninviteguest(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShouldverifyguestemail(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCanimportthirdpartycalendar(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.MeetSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.MeetSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.MeetSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMeetsettingid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCaninviteguest();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getShouldverifyguestemail();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getCanimportthirdpartycalendar();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional string meetSettingId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.getMeetsettingid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.MeetSettings} returns this
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.setMeetsettingid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool canInviteGuest = 2;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.getCaninviteguest = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.MeetSettings} returns this
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.setCaninviteguest = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool shouldVerifyGuestEmail = 3;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.getShouldverifyguestemail = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.MeetSettings} returns this
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.setShouldverifyguestemail = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool canImportThirdPartyCalendar = 4;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.getCanimportthirdpartycalendar = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.MeetSettings} returns this
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.setCanimportthirdpartycalendar = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 createdAt = 5;
 * @return {number}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.MeetSettings} returns this
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 updatedAt = 6;
 * @return {number}
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.MeetSettings} returns this
 */
proto.treeleaf.anydone.entities.MeetSettings.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.AccountSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.AccountSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.AccountSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountsettingid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    allowtwofactorauth: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    caninviteguest: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    createdat: jspb.Message.getFieldWithDefault(msg, 4, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.AccountSettings}
 */
proto.treeleaf.anydone.entities.AccountSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.AccountSettings;
  return proto.treeleaf.anydone.entities.AccountSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.AccountSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.AccountSettings}
 */
proto.treeleaf.anydone.entities.AccountSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountsettingid(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowtwofactorauth(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCaninviteguest(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.AccountSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.AccountSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.AccountSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountsettingid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAllowtwofactorauth();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getCaninviteguest();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string accountSettingId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.getAccountsettingid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.AccountSettings} returns this
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.setAccountsettingid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool allowTwoFactorAuth = 2;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.getAllowtwofactorauth = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.AccountSettings} returns this
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.setAllowtwofactorauth = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool canInviteGuest = 3;
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.getCaninviteguest = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.entities.AccountSettings} returns this
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.setCaninviteguest = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional int64 createdAt = 4;
 * @return {number}
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.AccountSettings} returns this
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 updatedAt = 5;
 * @return {number}
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.AccountSettings} returns this
 */
proto.treeleaf.anydone.entities.AccountSettings.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GloablTicketSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GloablTicketSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticketsettingid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    archiveticketby: jspb.Message.getFieldWithDefault(msg, 2, 0),
    createdat: jspb.Message.getFieldWithDefault(msg, 3, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GloablTicketSettings}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GloablTicketSettings;
  return proto.treeleaf.anydone.entities.GloablTicketSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GloablTicketSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GloablTicketSettings}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicketsettingid(value);
      break;
    case 2:
      var value = /** @type {!proto.treeleaf.anydone.entities.GloablTicketSettings.TicketAccessControl} */ (reader.readEnum());
      msg.setArchiveticketby(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GloablTicketSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GloablTicketSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicketsettingid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getArchiveticketby();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.TicketAccessControl = {
  UNKNOWN: 0,
  ADMIN: 1,
  EVERYONE: 2,
  TICKET_CREATOR: 3
};

/**
 * optional string ticketSettingId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.getTicketsettingid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GloablTicketSettings} returns this
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.setTicketsettingid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TicketAccessControl archiveTicketBy = 2;
 * @return {!proto.treeleaf.anydone.entities.GloablTicketSettings.TicketAccessControl}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.getArchiveticketby = function() {
  return /** @type {!proto.treeleaf.anydone.entities.GloablTicketSettings.TicketAccessControl} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.GloablTicketSettings.TicketAccessControl} value
 * @return {!proto.treeleaf.anydone.entities.GloablTicketSettings} returns this
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.setArchiveticketby = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional int64 createdAt = 3;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GloablTicketSettings} returns this
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 updatedAt = 4;
 * @return {number}
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.GloablTicketSettings} returns this
 */
proto.treeleaf.anydone.entities.GloablTicketSettings.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto.treeleaf.anydone.entities);
